version: '3.8'  # Specify the version

services:
  backend:
    build: ./
    ports:
      - 8081:8081
      - 6380:6379
    environment:
      - PORT=8081
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=database
      - DB_HOST=db
      - JWT_SECRET=ghj53dD3fghF&GH2#35s34sdfsd%fSDGsdg
      - COOKIE_SECRET=sDJLKsd235bn$asd&
      - NODE_ENV=development
      - ALLOWED_ORIGIN_1=http://localhost:5173
      - EMAIL_API_KEY=mlsn.15ff246a93594fa36dad0314359d18fa04cc1e113f38c90ed6d39717e20e789d
      - EMAIL_SERVICE_DOMAIN=MS_FXYSJq@trial-z86org8yx9klew13.mlsender.net
      - BASE_URL=http://localhost:8081
    volumes:
      - ./:/app-backend
      - /app-backend/node_modules
    restart: always
    depends_on:
      - db
    links: 
      - db
    container_name: auth-ts-back

  db:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    restart: always
    hostname: db
    container_name: auth-db

volumes:
  db_data: